//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Container()
        {
            this.Activity_Place = new HashSet<Activity_Place>();
        }
    
        public int container_idnum { get; set; }
        public string MBL_number { get; set; }
        public string container_number { get; set; }
        public string equipment_type { get; set; }
        public string vessel_code { get; set; }
        public string vessel_name { get; set; }
        public string voyage_number { get; set; }
        public string booking_number { get; set; }
        public string seal_number { get; set; }
        public string service_type { get; set; }
        public string shipper_reference_number { get; set; }
        public string pickup_number { get; set; }
        public string purchase_order_number { get; set; }
        public string IT_number { get; set; }
        public Nullable<int> lading_quantity { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string shipment_status_code { get; set; }
        public Nullable<System.DateTime> shipment_status_datetime { get; set; }
        public Nullable<System.DateTime> scheduled_sailing_date { get; set; }
        public Nullable<System.DateTime> scheduled_discharge_date { get; set; }
        public string place_of_receipt_location { get; set; }
        public string place_of_receipt_portname { get; set; }
        public string place_of_receipt_country { get; set; }
        public Nullable<System.DateTime> place_of_receipt_datetime { get; set; }
        public string port_of_loading_location { get; set; }
        public string port_of_loading_portname { get; set; }
        public string port_of_loading_country { get; set; }
        public Nullable<System.DateTime> port_of_loading_datetime { get; set; }
        public string port_of_discharge_location { get; set; }
        public string port_of_discharge_portname { get; set; }
        public string port_of_discharge_country { get; set; }
        public Nullable<System.DateTime> port_of_discharge_datetime { get; set; }
        public string place_of_delivery_location { get; set; }
        public string place_of_delivery_portname { get; set; }
        public string place_of_delivery_country { get; set; }
        public Nullable<System.DateTime> place_of_delivery_datetime { get; set; }
        public string MBL_destination_location { get; set; }
        public string MBL_destination_portname { get; set; }
        public string MBL_destination_country { get; set; }
        public Nullable<System.DateTime> MBL_destination_datetime { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> actual_door_delivery_time { get; set; }
        public string actual_door_delivery_location { get; set; }
        public Nullable<System.DateTime> arrival_at_first_port_of_load_time { get; set; }
        public string arrival_at_first_port_of_load_location { get; set; }
        public Nullable<System.DateTime> loaded_on_board_at_first_port_of_load_time { get; set; }
        public string loaded_on_board_at_first_port_of_load_location { get; set; }
        public Nullable<System.DateTime> actual_door_pickup_time { get; set; }
        public string actual_door_pickup_location { get; set; }
        public Nullable<System.DateTime> first_loaded_on_rail_under_outbound_time { get; set; }
        public string first_loaded_on_rail_under_outbound_location { get; set; }
        public Nullable<System.DateTime> loaded_on_truck_time { get; set; }
        public string loaded_on_truck_location { get; set; }
        public Nullable<System.DateTime> arrival_at_last_intermodal_hub_time { get; set; }
        public string arrival_at_last_intermodal_hub_location { get; set; }
        public Nullable<System.DateTime> carrier_released_time { get; set; }
        public string carrier_released_location { get; set; }
        public Nullable<System.DateTime> customs_released_time { get; set; }
        public string customs_released_location { get; set; }
        public Nullable<System.DateTime> carrier_and_customs_released_time { get; set; }
        public string carrier_and_customs_released_location { get; set; }
        public Nullable<System.DateTime> empty_container_picked_up_time { get; set; }
        public string empty_container_picked_up_location { get; set; }
        public Nullable<System.DateTime> freight_charges_settled_time { get; set; }
        public string freight_charges_settled_location { get; set; }
        public Nullable<System.DateTime> full_container_received_by_carrier_at_origin_time { get; set; }
        public string full_container_received_by_carrier_at_origin_location { get; set; }
        public Nullable<System.DateTime> customs_hold_time { get; set; }
        public string customs_hold_location { get; set; }
        public Nullable<System.DateTime> empty_container_returned_to_carrier_at_destination_time { get; set; }
        public string empty_container_returned_to_carrier_at_destination_location { get; set; }
        public Nullable<System.DateTime> departure_from_first_intermodal_hub_time { get; set; }
        public string departure_from_first_intermodal_hub_location { get; set; }
        public Nullable<System.DateTime> last_deramp_under_inbound_time { get; set; }
        public string last_deramp_under_inbound_location { get; set; }
        public Nullable<System.DateTime> discharged_from_vessel_at_last_port_of_discharged_time { get; set; }
        public string discharged_from_vessel_at_last_port_of_discharged_location { get; set; }
        public Nullable<System.DateTime> last_vessel_arrival_time { get; set; }
        public string last_vessel_arrival_location { get; set; }
        public Nullable<System.DateTime> first_vessel_departure_time { get; set; }
        public string first_vessel_departure_location { get; set; }
        public Nullable<System.DateTime> gate_out_full_at_inland_terminal_time { get; set; }
        public string gate_out_full_at_inland_terminal_location { get; set; }
        public Nullable<System.DateTime> gate_in_full_at_inland_terminal_time { get; set; }
        public string gate_in_full_at_inland_terminal_location { get; set; }
        public Nullable<System.DateTime> equipment_delayed_due_to_transportation_time { get; set; }
        public string equipment_delayed_due_to_transportation_location { get; set; }
        public Nullable<System.DateTime> arrived_at_facility_time { get; set; }
        public string arrived_at_facility_location { get; set; }
        public Nullable<System.DateTime> departed_from_facility_time { get; set; }
        public string departed_from_facility_location { get; set; }
        public Nullable<System.DateTime> loaded_at_port_time { get; set; }
        public string loaded_at_port_location { get; set; }
        public Nullable<System.DateTime> vessel_arrival_at_port { get; set; }
        public string vessel_arrival_at_location { get; set; }
        public Nullable<System.DateTime> discharged_from_vessel_at_port_of_discharge_time { get; set; }
        public string discharged_from_vessel_at_port_of_discharge_location { get; set; }
        public Nullable<System.DateTime> full_container_received_by_carrier_time { get; set; }
        public string full_container_received_by_carrier_location { get; set; }
        public Nullable<System.DateTime> vessel_departure_time { get; set; }
        public string vessel_departure_location { get; set; }
        public Nullable<System.DateTime> container_repacked_time { get; set; }
        public string container_repacked_location { get; set; }
        public Nullable<System.DateTime> container_vanned_at_origin_time { get; set; }
        public string container_vanned_at_origin_location { get; set; }
        public Nullable<System.DateTime> container_devanned_at_origin_time { get; set; }
        public string container_devanned_at_origin_location { get; set; }
        public Nullable<System.DateTime> container_vanned_at_destination_time { get; set; }
        public string container_vanned_at_destination_location { get; set; }
        public Nullable<System.DateTime> container_devanned_at_destination_time { get; set; }
        public string container_devanned_at_destination_location { get; set; }
        public Nullable<System.DateTime> container_transferred_time { get; set; }
        public string container_transferred_location { get; set; }
        public Nullable<System.DateTime> carrier_held_time { get; set; }
        public string carrier_held_location { get; set; }
        public Nullable<System.DateTime> container_available_time { get; set; }
        public string container_available_location { get; set; }
        public Nullable<System.DateTime> arrival_at_intermodal_hub_by_rail_time { get; set; }
        public string arrival_at_intermodal_hub_by_rail_location { get; set; }
        public Nullable<System.DateTime> loaded_on_rail_time { get; set; }
        public string loaded_on_rail_location { get; set; }
        public Nullable<System.DateTime> rail_move_time { get; set; }
        public string rail_move_location { get; set; }
        public Nullable<System.DateTime> loaded_time { get; set; }
        public string loaded_location { get; set; }
        public Nullable<System.DateTime> discharged_time { get; set; }
        public string discharged_location { get; set; }
        public Nullable<System.DateTime> container_picked_up_from_port_of_discharge_transhipment_port_time { get; set; }
        public string container_picked_up_from_port_of_discharge_transhipment_port_location { get; set; }
        public Nullable<System.DateTime> last_deramp_under_outbound_time { get; set; }
        public string last_deramp_under_outbound_location { get; set; }
        public Nullable<System.DateTime> transhipment_vessel_arrival_time { get; set; }
        public string transhipment_vessel_arrival_location { get; set; }
        public Nullable<System.DateTime> loaded_at_port_of_transhipment_time { get; set; }
        public string loaded_at_port_of_transhipment_location { get; set; }
        public Nullable<System.DateTime> discharged_at_port_of_transhipment_time { get; set; }
        public string discharged_at_port_of_transhipment_location { get; set; }
        public Nullable<System.DateTime> transhipment_vessel_departure_time { get; set; }
        public string transhipment_vessel_departure_location { get; set; }
        public Nullable<System.DateTime> intermodal_departure_from_last_port_of_discharge_time { get; set; }
        public string intermodal_departure_from_last_port_of_discharge_location { get; set; }
        public Nullable<System.DateTime> first_loaded_on_rail_under_inbound_time { get; set; }
        public string first_loaded_on_rail_under_inbound_location { get; set; }
        public Nullable<System.DateTime> picked_up_at_final_destination_for_delivery_time { get; set; }
        public string picked_up_at_final_destination_for_delivery_location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Place> Activity_Place { get; set; }
    }
}
