//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EDI_Messages> EDI_Messages { get; set; }
        public virtual DbSet<EDI315> EDI315 { get; set; }
        public virtual DbSet<EDI315_Detail> EDI315_Detail { get; set; }
        public virtual DbSet<EDI315_Detail_N9> EDI315_Detail_N9 { get; set; }
        public virtual DbSet<EDI315_Detail_R4> EDI315_Detail_R4 { get; set; }
        public virtual DbSet<EDI315_Detail_R4_DTM> EDI315_Detail_R4_DTM { get; set; }
        public virtual DbSet<Engines_Log> Engines_Log { get; set; }
    }
}
