//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI315_Detail_R4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDI315_Detail_R4()
        {
            this.EDI315_Detail_R4_DTM = new HashSet<EDI315_Detail_R4_DTM>();
        }
    
        public int Detail_R4_idnum { get; set; }
        public int msg_idnum { get; set; }
        public int EDI315_Detail_idnum { get; set; }
        public string port_function_code { get; set; }
        public string location_qualifier { get; set; }
        public string location_id { get; set; }
        public string port_name { get; set; }
        public string country_code { get; set; }
        public string terminal_name { get; set; }
        public string pier_number { get; set; }
        public string province_code { get; set; }
    
        public virtual EDI315_Detail EDI315_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDI315_Detail_R4_DTM> EDI315_Detail_R4_DTM { get; set; }
    }
}
