//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI315_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDI315_Detail()
        {
            this.EDI315_Detail_N9 = new HashSet<EDI315_Detail_N9>();
            this.EDI315_Detail_R4 = new HashSet<EDI315_Detail_R4>();
        }
    
        public int EDI315_Detail_idnum { get; set; }
        public int msg_idnum { get; set; }
        public int EDI315_idnum { get; set; }
        public string B4_SHC { get; set; }
        public Nullable<int> B4_request_number { get; set; }
        public string B4_status_code { get; set; }
        public string B4_date { get; set; }
        public string B4_status_time { get; set; }
        public string B4_status_location { get; set; }
        public string B4_equip_initial { get; set; }
        public string B4_equip_number { get; set; }
        public string B4_equip_status_code { get; set; }
        public string B4_equip_type { get; set; }
        public string B4_location_code { get; set; }
        public string B4_location_id { get; set; }
        public Nullable<int> B4_equip_check_digit { get; set; }
        public string Q2_vessel_code { get; set; }
        public string Q2_country_code { get; set; }
        public string Q2_date_1 { get; set; }
        public string Q2_date_2 { get; set; }
        public string Q2_date_3 { get; set; }
        public Nullable<int> Q2_lading_quantity { get; set; }
        public Nullable<decimal> Q2_weight { get; set; }
        public string Q2_weight_qualifier { get; set; }
        public string Q2_voyage_number { get; set; }
        public string Q2_reference_id_qualifier { get; set; }
        public string Q2_reference_id { get; set; }
        public string Q2_vessel_code_qualifier { get; set; }
        public string Q2_vessel_name { get; set; }
        public Nullable<decimal> Q2_volume { get; set; }
        public string Q2_volume_unit_qualifier { get; set; }
        public string Q2_weight_unit_code { get; set; }
        public int SE_included_segments_number { get; set; }
        public string SE_transaction_set_control_number { get; set; }
    
        public virtual EDI315 EDI315 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDI315_Detail_N9> EDI315_Detail_N9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDI315_Detail_R4> EDI315_Detail_R4 { get; set; }
    }
}
