//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI315
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDI315()
        {
            this.EDI315_Detail = new HashSet<EDI315_Detail>();
        }
    
        public int EDI315_idnum { get; set; }
        public int msg_idnum { get; set; }
        public string ISA_auth_info_qualifier { get; set; }
        public string ISA_auth_info { get; set; }
        public string ISA_security_info_qualifier { get; set; }
        public string ISA_security_info { get; set; }
        public string ISA_interchange_id_qualifier_1 { get; set; }
        public string ISA_interchange_sender_id { get; set; }
        public string ISA_interchange_id_qualifier_2 { get; set; }
        public string ISA_interchange_receiver_id { get; set; }
        public string ISA_interchage_date { get; set; }
        public string ISA_interchange_time { get; set; }
        public string ISA_interchange_control_standards_id { get; set; }
        public string ISA_interchange_control_version_number { get; set; }
        public string ISA_interchange_control_number { get; set; }
        public string ISA_ack_requested { get; set; }
        public string ISA_usage_indicator { get; set; }
        public string ISA_component_element_separator { get; set; }
        public string GS_functional_id_code { get; set; }
        public string GS_app_sender_code { get; set; }
        public string GS_app_receiver_code { get; set; }
        public string GS_date { get; set; }
        public string GS_time { get; set; }
        public string GS_group_control_number { get; set; }
        public string GS_reponsible_agency_code { get; set; }
        public string GS_industry_id_code { get; set; }
        public System.DateTime created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDI315_Detail> EDI315_Detail { get; set; }
    }
}
