//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI315_Detail_N9
    {
        public int Detail_N9_idnum { get; set; }
        public int msg_idnum { get; set; }
        public int EDI315_Detail_idnum { get; set; }
        public string reference_id_qualifier { get; set; }
        public string reference_id { get; set; }
        public string free_form_description { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string time_code { get; set; }
    
        public virtual EDI315_Detail EDI315_Detail { get; set; }
    }
}
