//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI315_Detail_R4_DTM
    {
        public int Detail_R4_DTM_idnum { get; set; }
        public int msg_idnum { get; set; }
        public int Detail_R4_idnum { get; set; }
        public string datetime_qualifier { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string time_code { get; set; }
    
        public virtual EDI315_Detail_R4 EDI315_Detail_R4 { get; set; }
    }
}
