//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI_Messages
    {
        public int msg_idnum { get; set; }
        public string msg_type { get; set; }
        public string msg_body { get; set; }
        public System.DateTime received_date { get; set; }
        public string file_name { get; set; }
        public string process_status { get; set; }
    }
}
