//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI315_Engine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engines_Log
    {
        public int log_id { get; set; }
        public string msg_type { get; set; }
        public Nullable<int> msg_idnum { get; set; }
        public Nullable<int> EDI_idnum { get; set; }
        public Nullable<int> Detail_idnum { get; set; }
        public string log_msg { get; set; }
        public System.DateTime created_date { get; set; }
    }
}
